# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b4d811c5eda90cc850aa6ed1d3b1f7f1f5cd1d02ec123514903222ed74522d69ff89251d317a9b4c64e0c4573410eb9756f39b35175aeb91e4484823d3e59bd

test:
  secret_key_base: 3730d497e81aac8396337d1d37a79d7ac71070b402a199f37d7596a88a369f86b69486ba1843b033e035b33ead20706955e5f4a6a520c9e756b338da7308eca2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
